
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
// import { usePathname } from "next/navigation";

export const metadata: Metadata = {
  title: "Coreco - Collaborative Code Editor",
  description: "Generated by create next app",
};

export default function HomeLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            <main className="">
                {children}
            </main>
        </>
    );
}